name: OpenTofu CI

on: [workflow_dispatch]

jobs:
  opentofu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up OpenTofu
      run: |
           wget https://github.com/opentofu/opentofu/releases/download/v1.6.0/tofu_1.6.0_amd64.deb
           sudo dpkg --install tofu_1.6.0_amd64.deb
           sudo mv /usr/bin/tofu /usr/local/bin/opentofu
           opentofu version

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Run AWS Command
      run: aws sts get-caller-identity

    - name: Initialize OpenTofu
      run: opentofu init

    - name: Validate OpenTofu configuration
      run: opentofu validate

    - name: Apply OpenTofu configuration
      run: opentofu apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
