name: OpenTofu CI

on: [workflow_dispatch]

jobs:
  opentofu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up OpenTofu
      run: wget https://github.com/opentofu/opentofu/releases/download/v1.6.0/tofu_1.6.0_amd64.deb
           sudo dpkg --install tofu_1.6.0_amd64.deb
           mv /usr/bin/ tofu /usr/local/bin/opentofu
           opentofu version

    - name: Initialize OpenTofu
      run: opentofu init

    - name: Validate OpenTofu configuration
      run: opentofu validate

    - name: Plan OpenTofu configuration
      run: opentofu plan

    - name: Apply OpenTofu configuration
      run: opentofu apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
